### ISSUE TITLE
Is Commit button committing to database table?

### ISSUE THREAD

**Issue by mortoza** [tyl/field-binder#6]
Hi
A quick question, Is CRUD commit button is persisting data to database in field-binder?

**Comment by evacchi** [comment]
It depends on which Container is attached to the Navigation/FieldBinder/BeanTable. e.g., when you are using a JPAContainer, the commit button will invoke `commit()` on the JPAContainer; likewise, if it is a MongoContainer, the `addEntity()` method will be invoked (and `commit()` in the case of BeanTable+BufferedMongoContainer). In the case of plain ListContainer, which has no equivalent to a `commit` on the data source, nothing is done: you have to add your custom logic through event listeners

**Comment by mortoza** [comment]
Thanks for the feedback. Is there any other container with commit button, e.g JPAContainer ?

**Comment by mortoza** [comment]
Sorry, please ignore my above comments.

I have tried JPAContainer but unfortunately it didn't commit to database. Any clue?

**Comment by evacchi** [comment]
> Thanks for the feedback. Is there any other container with commit button, e.g JPAContainer ?

MongoContainer is supported support out-of-the-box

> I have tried JPAContainer but unfortunately it didn't commit to database. Any clue?

As I explained in the other issue, I believe you should check your JPA configuration. I advise you to please refer to the Vaadin forums for support with JPA configuration and other FieldBinder-unrelated issues.

You can find more information on the FieldBinder add-on and the supported Containers on https://github.com/tyl/documentation/tree/master/field-binder and related subfolders
