### ISSUE TITLE
setVisibleColumns in detail table doesn't work with ListContainer

### ISSUE THREAD

**Issue by mortoza** [tyl/field-binder#7]
Hi
I like your component and that's why trying to use it in my test project as I am new to Vaadin and coming back with a lot of questions. I hope you don't feel bored. 

When I am using ListContainer, setVisibleColumn is not working, it is always showing all the columns of the detail table. However, it works with the same code when using JPAContainer. Is it something that is not supposed to work using ListContainer?

Thanks for your comments/help.
Mortoza

**Comment by evacchi** [comment]
It might be a bug in Viritin's ListContainer. I'll investigate. Make sure you are using the last version of Viritin. See the Viritin Add-on page: https://vaadin.com/directory/-/directory/addon/viritin

**Comment by mortoza** [comment]
Hi
Thanks. Yes, I am using the latest version 1.26 of Viritin.

**Comment by evacchi** [comment]
I think this bug should now be fixed in v1.3
