### ISSUE TITLE
NotSerializableException

### ISSUE THREAD

**Issue by rbuchli** [tyl/field-binder#8]
Hi Edoardo

Thank you very much for your work on this addon! I'm on the way to use in for a database project. 

Would it be possible to make fieldbinder serializable? I always get the following message when I restart tomcat:
java.io.WriteAbortedException: writing aborted; java.io.NotSerializableException: org.tylproject.vaadin.addon.fieldbinder.FieldBinder$1
Caused by: java.io.NotSerializableException: org.tylproject.vaadin.addon.fieldbinder.FieldBinder$1

I know, this is not really a problem, it just would help for debugging my own faults having less messages ....

Best regards,
Reto

**Comment by evacchi** [comment]
I have just pushed v1.2.3 which should fix this minor annoyance :)

**Comment by rbuchli** [comment]
Wow, what a service (time)!
Great. 
Thank you!
